### ISSUE TITLE
Icons not loading

### ISSUE THREAD

**Issue by jakubsvobodacz** [SQL-MisterMagoo/Blazor.PWA.MSBuild#2]
I added icon-192.png and icon-512.png to my wwwroot folder but they do not work on my iphone. They show up correctly on the desktop, so I belive the path to the images is not the case.

**Comment by SQL-MisterMagoo** [comment]
Hi, I am not sure as I don't use Apple devices, but a quick Google search found this article (and further searches seem to confirm it) that may help.

It seems iOS ignores the web app manifest icons - why stick to a standard? - so you need to provide an iOS specific "apple-touch-icon" yourself separately from the PWA "stuff".

https://medium.com/appscope/designing-native-like-progressive-web-apps-for-ios-1b3cdda1d0e8

**Comment by jakubsvobodacz** [comment]
thanks1 problem solved
