### ISSUE TITLE
PWA install option not available when using Azure Web Service

### ISSUE THREAD

**Issue by mrgitmr** [SQL-MisterMagoo/Blazor.PWA.MSBuild#20]
I can't get the PWA install option to work(does not show) when publishing the app to Azure
using web deploy.
It might be because these files creates error 404 on load:
"/css/open-iconic/FONT-LICENSE",
"/css/open-iconic/font/fonts/open-iconic.otf",
"/css/open-iconic/ICON-LICENSE",
"/css/open-iconic/README.md",

Is it possible to remove these files from the Service worker?

**Comment by SQL-MisterMagoo** [comment]
Sure, you can add it remove anything you like

**Comment by mrgitmr** [comment]
Well the Service worker gets updated at every build?

**Comment by mrgitmr** [comment]
Or to be clear it is updated during the build that is part of the publish to azure in VS 2019 16.5.0 Preview 2

**Comment by SQL-MisterMagoo** [comment]
So I guess your publish profile is set to delete existing files before build, because the default is not to overwrite an existing file.

You could remove the PWA build package from the release configuration OR use the ServiceWorkerPreCacheExcludeFiles property to list the files you want to exclude.

**Comment by mrgitmr** [comment]
I tried the ServiceWorkerPreCacheExcludeFiles but i might have misunderstood the configuration i tried:
<ServiceWorkerPreCacheExcludeReleaseFiles>
      $(OutputPath)css/open-iconic/FONT-LICENSE;
    </ServiceWorkerPreCacheExcludeReleaseFiles>
But it(FONT-LICENSE) is still included in the overwritten ServiceWorker.js

**Comment by SQL-MisterMagoo** [comment]
Try using WWWRoot instead of OutputPath, as these are not imported content, but regular static files

**Comment by mrgitmr** [comment]
Thanks It works now !
