### ISSUE TITLE
How to conitnously update pwa

### ISSUE THREAD

**Issue by KuraiAndras** [SQL-MisterMagoo/Blazor.PWA.MSBuild#21]
I created a property group like this:
```xml
  <PropertyGroup>
    <ServiceWorkerForce>true</ServiceWorkerForce>
  </PropertyGroup>
```

But i still need to add 
```xml
  <PropertyGroup>
    <ServiceWorkerForce>true</ServiceWorkerForce>
    <ServiceWorkerCacheVersion>2</ServiceWorkerCacheVersion>
  </PropertyGroup>
```

and update the cache version every time i want to add changes to the blazor project.
How can I always keep the build fresh so when I launch the app the service worker/cache version updates autmatically?

**Comment by SQL-MisterMagoo** [comment]
Try something like this
https://github.com/Blazored/Gitter/blob/d85409d53bd557547cb52d09c6014e8ba78f1fe3/src/Directory.Build.props#L9

**Comment by KuraiAndras** [comment]
Thanks, this works
