### ISSUE TITLE
Disable on localhost

### ISSUE THREAD

**Issue by thopdev** [SQL-MisterMagoo/Blazor.PWA.MSBuild#3]
Would it be possible to disable the creation of the pwa on localhost so i don't have to keep updating the version of clear cache every update i do?

**Comment by SQL-MisterMagoo** [comment]
Yes, it's a manual change, but I'll see about adding it as an option sometime today.

In your ServiceWorkerRegister.js file, change the `window.updateAvailable` declaration like this

``` diff
window.updateAvailable = new Promise(function (resolve, reject) {
+    if (window.location.hostname !== 'localhost') {
        if ('serviceWorker' in navigator) {
            navigator.serviceWorker.register(serviceWorkerFileName)
                .then(function (registration) {
... // lines removed for brevity
                .catch(error =>
                    console.log('Service worker registration failed, error:', error));
        }
+    }
});

```

You will need to manually unregister the current service worker in your browser and delete your existing cache as well.

**Comment by thopdev** [comment]
Thank you, i will add it. It would make debugging and developing a little bit easier.
