### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by WillianGruber** [SQL-MisterMagoo/Blazor.PWA.MSBuild#7]
In a demo app, I was able to install the PWA and it launched successfully.
Closing the PWA, and opening the blazor app again with F5 or directly typing the url does not redirect to the installed PWA. Is there a way to accomplish this?

Thanks!

**Comment by chucker** [comment]
My understanding is:

* this won't work on iOS
* on Android, this will work automatically: https://developers.google.com/web/fundamentals/integration/webapks

What device are you on?

**Comment by SQL-MisterMagoo** [comment]
Please open a new Issue of you still require help with this.
Thanks @chucker for the answer

**Comment by WillianGruber** [comment]
@chucker in a chrome browser, PC.
Sorry for the late answer
